### ISSUE TITLE
Migrate to netstandard

### ISSUE THREAD

**Issue by HellBrick** [HellBrick/AsyncCollections#14]

**Comment by tlycken** [comment]
Any progress on this? Can I help?

**Comment by HellBrick** [comment]
There's not much progress to report, I kind of put this project on the back burner. My original plan was to switch to `netstandard` in the 2.0 release along with a bunch of other breaking changes that need a lot more work. However, if you're interested in a `netstandard` version of what's currently up on Nuget, I can do just that without blocking on more substantial work.

**Comment by tomasaschan** [comment]
Yeah, the `AsyncQueue` turned out to be exactly what I needed, but since I'm running on .NET Core (on Linux) I want to feel sure that it'll work well. And get rid of that build warning ;)

I think I could quite easily help port the project files to the new SDK and add a `netstandard2.0` build target, however it seems you have a few build targets there for your publishing process, which might - or might not - be better handled by e.g. `dotnet pack` and `dotnet push`, so I don't know what you want to do with those.

**Comment by HellBrick** [comment]
I performed the project migration yesterday, so most of the work here is done ;) Now I just need to settle on which netstandard versions to target (I'm currently thinking 1.3 + 2.0), double-check everything and publish the final package, I'll try to finish it today/tomorrow. In the meantime, if you're interested in trying what might be called an RC, I've uploaded a pre-release version to Nuget, it will be up [here](https://www.nuget.org/packages/AsyncCollections/2.0.0-rc) once the package is validated.

**Comment by tomasaschan** [comment]
Sweet! I'll give it a spin later today or tomorrow :)

**Comment by megakid** [comment]
Good job on lib, looks good.  Quick note, can you also target netfx - at most, `net461` - in your release?  Making people pull in the netstandard version in their full netfx apps sometimes leads to trouble (which is why most ported libs multitarget to retain a full fx target like `net461`).  

I've only just come across this lib and would like to try it.

PS does the `AsyncCollection` gaurentee FIFO awaiter order? e.g. if there's no items and awaiters A, B, C arrive (in that logical order) with `TakeAsync`, will A always get the take the first item to arrive, then B etc? I had a dip into the code and it seems that way.
Is this the same for `AsyncQueue` also (code wasn't as straightforward to follow here!)?

**Comment by tomasaschan** [comment]
@HellBrick I'm sorry I never got back to you on this. For reasons unrelated to this, I had to re-think the approach I was using that made me need this package, so I'm no longer depending on it (and thus have no good test case for the new version at the moment).

If there's any way I can help out anyway, just let me know! :)
